config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :restaurants do
  	resources :reviews, except: [:show, :index]
  end
  
  get 'pages/about'
  get 'pages/top3'

  root 'restaurants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	 mount_uploader :image, ImageUploader

	 has_many :reviews

	 validates :name, :address, :phone, :website, :image, presence: true

	 
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant

	validates :rating, :comment, presence: true

	#http://guides.rubyonrails.org/active_record_validations.html
	#2.8 numericalityを参考にvalidation
	validates :rating, numericality:{
		only_integer: true,
		greater_than_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "This should be a number between 1 to 5"
	}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy 

  validates :username, presence: true        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def top3
  	
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search,:index, :show]
  

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @review = Review.where(restaurant_id: @restaurant.id).order('created_at DESC')
    if @review.blank?
      @avg_review = 0
    else
      @avg_review = @review.average(:rating).round(2)
    end

  end




  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end

    # respond_to do |format|
    #   if @restaurant.save
    #     format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
    #     format.json { render :show, status: :created, location: @restaurant }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @restaurant.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_path, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_restaurant
  before_action :authenticate_user!

  # before_action :check_user, only: [:edit, :update, :destroy]



  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @restaurant, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @restaurant, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # def check_user
    #   unless (@review.user_id == current_user.id) || (current_user.admin?)
    #     redirect_to root_path, alert: "Only creater can edit this"
    #   end
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

<!-- Optional jQuery-->
<!-- <script
  src="//code.jquery.com/jquery-3.3.1.min.js">
  </script>
 -->
 
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>

app/views/layouts/_footer.html.erb
<!-- <footer style="position: fixed; bottom: 0; width: 100%; height: 50px; text-align: center">
	<br>
	<p>2018 Catch Cafe. All rights reserved.</p>
</footer> -->

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Catch Cafe</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/top3">人気カフェトップ３</a></li>
        <li><a href="/pages/about">Catch Cafeとは？<span class="sr-only">(current)</span></a></li>  
      </ul>
      
  
      


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "会員情報", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %> 
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catch Cafe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/bootstrap' %>
    
  </head>

  <body>
	
	  <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <% flash.each do |name,msg| %>
    <% if msg.is_a?(String) %>
     <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable" >
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
   <% end %>
 <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>

    <p style="margin-top: 80px; text-align: center;">2018 Catch Cafe. All rights reserved.</p>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<!--　▼ ジャンボトロン　 -->
    <div class="jumbotron" style="background-image: url('https://s3-ap-northeast-1.amazonaws.com/restaurant-storage/catcafe.jpg'); width:100%; background-size: cover; height: 400px;">
      <div class="container" style="font-weight: bold;">
        <h1 style="font-weight: bold;">Catch Cafeへようこそ</h1>
        <h2>Catch Cafeでは、様々な動物のカフェを探すことができます。</h2>
        <h2>ぜひ、あなたにぴったりのカフェを探してみてはいかがでしょうか？</h2>

       
      </div>
    </div>
<!--　▲ ジャンボトロン　 -->


			<div class="row">
        <div class="col-md-12 col-sm-6">
            <hr>
            
            <h2>最新情報</h2>
            <h3>カワウソカフェが新宿にオープン/2018年6月1日</h3>
            <h3>ハリネズミカフェが六本木にオープン/2018年3月1日</h3>
            <p>新しいカフェを随時更新中</p>
      </div>
    </div>
       

app/views/pages/top3.html.erb
<h1>人気カフェトップ３(Catch Cafe調べ)</h1>
<hr>
<br>
<div class="container">
	<h2>1位 カワウソもいるウサギカフェが新宿三丁目店</h2>
	<hr>
	<div class="row">
		<div class="col-sm-4">
			<img src="https://s3-ap-northeast-1.amazonaws.com/restaurant-storage/kawauso.jpeg" class="img-responsive">
		</div>

		<div class="col-sm-8">
			<h3>カワウソが大人気</h3>
			<p>2018年5月にオープンし、綺麗な内装もあり、連日お客さんが多く来られているようです。外国のお客様も多いことから、事前に混雑状況を確認することをオススメいたします。</p>
		</div>

	</div>


	<hr  style="margin-top: 100px;margin-bottom: 50px;">
	<h2>2位 カハリネズミ専門カフェ ちくちくCAFE 東京・渋谷</h2>
<hr>
		<div class="row">
		<div class="col-sm-4">
			<img src="https://s3-ap-northeast-1.amazonaws.com/restaurant-storage/harinezumi.jpg" class="img-responsive">
		</div>

		<div class="col-sm-8">
			<h3>手に持てるハリネズミが大好評</h3>
			<p>これまでなかなか触ることのなかったハリネズミが大人気。家で飼うことも難しいので、一度訪れたらやみつきになるという噂。</p>
		</div>

	</div>


		<hr  style="margin-top: 100px;margin-bottom: 50px;">
	<h2>3位 あうるぱーく　フクロウカフェ池袋/東京</h2>
	<hr>
		<div class="row">
		<div class="col-sm-4">
			<img src="https://s3-ap-northeast-1.amazonaws.com/restaurant-storage/fukurou.jpeg" class="img-responsive">
		</div>

		<div class="col-sm-8">
			<h3>凛々しい目と小さいが圧倒されるフクロウ</h3>
			<p>おやつの時間には、エサをあげられることもあり、多くのお客様が訪れる。その爪は鋭くかっこいいと大人気。</p>
		</div>

	</div>


</div>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, html: {multipart: true } ) do |form| %>
  <% if @restaurant.errors.any? %>
     <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h4><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :名前 %>
    <%= form.text_field :name, id: :restaurant_name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :住所 %>
    <%= form.text_field :address, id: :restaurant_address, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :電話番号 %>
    <%= form.text_field :phone, id: :restaurant_phone , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ウェブサイト %>
    <%= form.text_field :website, id: :restaurant_website , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :画像添付 %>
    <%= form.file_field :image, id: :restaurant_image , class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "新規カフェ登録",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h2>カフェの編集</h2>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'カフェを表示', @restaurant , class: "btn btn-link"%> |
<%= link_to '一覧に戻る', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<div class="jumbotron" style="background-color: #F9FCCF; border: 1px solid #9999ff;color:#b30059; font-weight: bold;">
  <h2>Catch Cafeで今人気の動物カフェを探しませんか？</h2>
  <p>あなたのお気に入りのカフェが見つかるはず！</p>
</div>


<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>カフェの名前</th>
      <th>住所</th>
      <th>電話番号</th>
      <th></th>
      <% if user_signed_in?  && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.website %></td>
        <% if user_signed_in?  && current_user.admin? %>
          <td><%= link_to '編集', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to '削除', restaurant, method: :delete, data: { confirm: '削除してもよろしいですか?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in?%> <!--  && current_user.admin? ログインユーザとアドミン-->
  <%= link_to '新しいカフェの登録', new_restaurant_path,class:"btn btn-success" %>
<% end %>

app/views/restaurants/new.html.erb
<h1>カフェの新規登録</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to '戻る', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in?  && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.website %></td>
        <% if user_signed_in?  && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @restaurant.image_url %>
		<br>
		<div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@review.length} reviews" %></em>
		<h2>
		  <%= @restaurant.name %>
		</h2>
		

		<p>
		  <strong>住所:</strong>
		  <%= @restaurant.address %>
		</p>

		<p>
		  <strong>電話番号:</strong>
		  <%= @restaurant.phone %>
		</p>

		<p>
		  <strong>URL:</strong>
		  <%= link_to @restaurant.website, @restaurant.website %>
		</p>
		
			<%= link_to "レビューを書く" ,new_restaurant_review_path(@restaurant),class: "btn btn-primary" %><br><br>
				<iframe
				  width="280"
				  height="280"
				  frameborder="0" style="border:0"
				  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBDL6bOHeM9-DuSKdX0i-HbTXodbvwCY28
				    &q=<%= @restaurant.address.parameterize %> &zoom=14" allowfullscreen>
				</iframe>
<br>
			<% if user_signed_in? %>
				<% if  current_user.admin? %>
					<%= link_to 'カフェの編集', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
				<% end %>
			<% end %>
			<%= link_to '一覧に戻る', restaurants_path, class: "btn btn-link" %>
	</div>


	<div class="col-md-8">
	<% if @review.blank? %>
		<h3>まだレビューがありません。是非、書いてみませんか？</h3>
	<% else %>
		
		<table class="table">
			<thead>
				<tr>
					<td style="">
						<div class="col-md-3"></div>
						<div class="col-md-9"></div>
					</td>
				</tr>
			</thead>

			<tbody>
				<% @review.each do |review| %>
				<tr>
					<td>
						<h4><%= "#{review.user.username}" %></h4>
						<p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
					</td>
			 
					<td>
						<!-- raty.jsを使う場合は下記のコードになるはずだが、機能しない。
							<div class="star-rating" data-score= <%= review.rating %> ></div> -->
							<div class="star-rating" data-score= <%= review.rating %> ></div>
						<!--<div class="star-rating" data-score=<%= review.rating %> ></div> --> 
						<!-- <div class="star-rating" data-score="<%= review.rating %>"></div> -->
							<!-- <div id="test"></div> -->
							<!-- <div id="star"></div>--> 
							 <!-- <p><%= review.rating %></p> --> 
							

							<!-- 改行を反映させるためのコマンド↓ -->
							<p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
							<% if user_signed_in? %>
								<% if review.user == current_user || current_user.admin? %>
									<%= link_to "Edit", edit_restaurant_review_path(@restaurant,review) %>
									<%= link_to "Delete", restaurant_review_path(@restaurant,review), method: :delete %>
								<% end %>
							<% end %>

						</td>
					</tr>
				<% end %>
			</tbody>

		</table>
	<% end %>
	</div>
</div> 










<!-- 
下記のサイトから持ってきた
https://stackoverflow.com/questions/35167149/im-using-raty-js-star-rating-system-how-do-i-show-the-equivalent-integer-value
star-ratingの部分を変更した
 -->


<script>
    $('.star-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function() {
            return $(this).attr('data-score');
        }
    });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <p style="font-weight: bold;">スターの数を選んで下さい</p>
    <div id="star-rating"></div>
</div> 
  <br>

  <!-- <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating, class: "form-control" %>
  </div>  -->

  <!--<div class="form-group">
    <div id="star-rating"></div>
  </div>-->

  <div class="form-group">
    <%= form.label :コメントを書いてくだい %>
    <%= form.text_area :comment, id: :review_comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "投稿する", class: "btn btn-primary"  %>
  </div>
<% end %>


<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>


<%= link_to 'Back',  restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h3>新規レビュー入力</h3>

<%= render 'form', review: @review %>
<br>
<%= link_to '戻る', restaurant_path(@restaurant) %>